{
# target variable
  'target_variable' : "team1_victory",

# possible scoring ranges per player per game for minimal player base, min and max inclusive
  'scoring_ranges' : {
    'a1' : [1,2],
    'a2' : [1,2],
    'a3' : [1,2],
    'b1' : [0,1],
    'b2' : [0,1],
    'b3' : [0,1],
    'c1' : [-1,1],
    'c2' : [-1,1],
    'd1' : [-2,0],
    'd2' : [-2,0]
    },
# possible scoring ranges per play per game for an expanded player base, min and max inclusive
  'scoring_ranges_extended' : {
      's1' : [1,3],
      's2' : [1,3],
      'a1' : [1,2],
      'a2' : [1,2],
      'a3' : [1,2],
      'a4' : [1,2],
      'b1' : [0,1],
      'b2' : [0,1],
      'b3' : [0,1],
      'b4' : [0,1],
      'b5' : [0,1],
      'b6' : [0,1],
      'b7' : [0,1],
      'b8' : [0,1],
      'b9' : [0,1],
      'c1' : [-1,1],
      'c2' : [-1,1],
      'c3' : [-1,1],
      'c4' : [-1,1],
      'c5' : [-1,1],
      'c6' : [-1,1],
      'c7' : [-1,1],
      'c8' : [-1,1],
      'c9' : [-1,1],
      'd1' : [-2,0],
      'd2' : [-2,0],
      'd3' : [-2,0],
      'd4' : [-2,0],
      'n1' : [0,0],
      'n2' : [0,0]
    }
}